version: '3'

services:
  react:
    env_file: .env
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./build:/usr/share/nginx/html/build
    ports:
      - ${NGINX_EXT_PORT}:80